name: shablon
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ###
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  flutter_svg: ^2.1.0
  intl: ^0.19.0
  go_router: ^15.1.1
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.4
  dio: ^5.8.0+1
  sqflite: ^2.4.2
  path: ^1.9.1
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: w400
      fonts:
        - asset: assets/fonts/SFProText-Regular.ttf
    - family: w500
      fonts:
        - asset: assets/fonts/SFProText-Medium.ttf
    - family: w600
      fonts:
        - asset: assets/fonts/SFProText-SemiBold.ttf
    - family: w700
      fonts:
        - asset: assets/fonts/SFProText-Bold.ttf
    - family: w800
      fonts:
        - asset: assets/fonts/SFProText-Heavy.ttf